"""Add RetentionAlert

Revision ID: 917336533375
Revises: 2aaeb739f625
Create Date: 2026-09-08 04:07:06.920703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917336533375'
down_revision: Union[str, None] = '2aaeb739f625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retention_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_alerts_tenant_id'), 'retention_alerts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retention_alerts_tenant_id'), table_name='retention_alerts')
    op.drop_table('retention_alerts')
    # ### end Alembic commands ###
