"""Phase 1 schema extensions

Revision ID: de48cdb79722
Revises: 8071240ab2fa
Create Date: 2026-08-18 01:18:52.629803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de48cdb79722'
down_revision: Union[str, None] = '8071240ab2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_performance_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('prediction_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('predicted_value', sa.String(), nullable=False),
    sa.Column('actual_value', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_accurate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_performance_metrics_tenant_id'), 'model_performance_metrics', ['tenant_id'], unique=False)
    op.create_table('churn_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_index(op.f('ix_churn_scores_tenant_id'), 'churn_scores', ['tenant_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('policy_type_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('quote_data', sa.JSON(), nullable=True),
    sa.Column('quoted_premium', sa.Float(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['policy_type_id'], ['policy_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_tenant_id'), 'quotes', ['tenant_id'], unique=False)
    op.add_column('applications', sa.Column('quote_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'applications', 'quotes', ['quote_id'], ['id'])
    op.add_column('claims', sa.Column('assigned_adjuster_id', sa.UUID(), nullable=True))
    op.add_column('claims', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('claims', sa.Column('sla_deadline', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'claims', 'users', ['assigned_adjuster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_column('claims', 'sla_deadline')
    op.drop_column('claims', 'priority')
    op.drop_column('claims', 'assigned_adjuster_id')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'quote_id')
    op.drop_index(op.f('ix_quotes_tenant_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_churn_scores_tenant_id'), table_name='churn_scores')
    op.drop_table('churn_scores')
    op.drop_index(op.f('ix_model_performance_metrics_tenant_id'), table_name='model_performance_metrics')
    op.drop_table('model_performance_metrics')
    # ### end Alembic commands ###
